apiVersion: v1
kind: Service
metadata:
  name: foodadvisor-frontend
spec:
  selector:
    app: foodadvisor
    component: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
