apiVersion: v1
kind: Service
metadata:
  name: foodadvisor-frontend-np
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: foodadvisor
    component: frontend
  type: NodePort
