apiVersion: v1
kind: Service
metadata:
  name: foodadvisor-backend-np
  namespace: default
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: foodadvisor
    component: backend
  type: NodePort
